trainingInput:
    scaleTier: CUSTOM
    region: us-central1
    masterType: n1-standard-4
    masterConfig:
        acceleratorConfig: 
            count: 1
            type: NVIDIA_TESLA_T4 #Other options: K80, P4, P100, T4, V100 - most expensive for some reason


